error: directly return an error without jump
This patch changes the current error handling mechanism to directly return an
error code without goto fn_fail.  This enhances the debugging information since
Argobots can print the exact line that returns an error.  This change also
shortens functions.